IF
	See([GOODCUTOFF])
	!AreaCheck("AR5201")
	Global("SaidPiece","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("SaidPiece","LOCALS",1)
		DisplayStringHead(Myself,70663) // Hsss!  If we baatezu are to be trapped forever in this maze, than we shall feast on the hearts of mortals!!
		Continue()
END

IF
	See([GOODCUTOFF])
	Global("hostile","LOCALS",0)
	Global("BatEnemy","GLOBAL",1)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		SetGlobal("hostile","LOCALS",1)
		Enemy()
END
